=== lukaszkurczab/patternly-content/schemas/publishing/content-activation-record.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "content-activation-record-v1",
  "type": "object",
  "additionalProperties": false,
  "required": ["activationSchemaVersion", "activationId", "trackId", "familyId", "contentVersion", "taxonomyVersion", "itemCoverage"],
  "properties": { "activationSchemaVersion": { "const": 1 }, "activationId": { "type": "string", "minLength": 1 }, "trackId": { "type": "string", "minLength": 1 }, "familyId": { "type": "string", "minLength": 1 }, "contentVersion": { "type": "string", "minLength": 1 }, "taxonomyVersion": { "type": "string", "minLength": 1 }, "itemCoverage": { "type": "array", "minItems": 1, "items": { "type": "object", "required": ["itemId", "itemFingerprint", "approvalId"] } } }
}

=== lukaszkurczab/patternly-content/manual/activations/cloud-certification/gcp-ace-0007.json
{"activationId":"activation:cloud-certification:gcp-ace-0007","activationSchemaVersion":1,"contentVersion":"gcp-ace-0007","familyId":"certification","itemCoverage":[{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"2a20ce3135c93deca635f9f8ccaee0f084b2e20f22035dd5adc4071b6a2c6ad3","itemId":"ace-q-0001"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"e3d1dac23bf9ed3561ec80a3d37d92c185d4e9626712c58aac65f285e5754ea8","itemId":"ace-q-0002"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"bf0db63581967eeebefdc3a563445fac949945ef3d3652b8d3088963e83b490e","itemId":"ace-q-0003"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"91d341c45e84d1d84ee9e344d559e0d86ae744e044c1c399a2e26dcc81541c8d","itemId":"ace-q-0004"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"9bd22552745005e2b5200e175a2c68ef68394f0f9024fe76e94777b2c39473bb","itemId":"ace-q-0005"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"7420e726c825d79234a83518a1b2717c150344401d6bb6031ebc2f5056dae8e6","itemId":"ace-q-0006"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"9e125ea4126a9052219ed273566af0f94f6c87b7a0374ec22736eb6bffe2fb7e","itemId":"ace-q-0007"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"f90bf0f647b7c37089b9fc1cae5ec5f029c84066f1423fbbc3f32d2023ae4b56","itemId":"ace-q-0008"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"9e735018d192e9f6b5d15c8cd9a1c6881be66fc568b28752b25530dc35b9a08f","itemId":"ace-q-0009"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"d21fbf8dc8293d9ef1c44bc5a69bf0c3abf79f781737346373ebcb4fc991c64f","itemId":"ace-q-0010"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"9885c096e5814c9b2b3ce8039bcdeb8db73fc514b77c6dede87c32d19ec99441","itemId":"ace-q-0011"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"d65596d891cc244bef8c6ded200ab005ec0e2a6ca0981a87123ec31d03a98f2c","itemId":"ace-q-0012"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"0f374438cac6c4e6ddbf971ddf1a0add8789c5db521290ad459e595be61a0ef1","itemId":"ace-q-0013"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"8f19e15a4561097b96fd63ca0159291bcbef4fcfde3894d268054f319ccef583","itemId":"ace-q-0014"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"8937cca5c099447eeca9196a32578cfabf78305731452cce78de51e2410f7608","itemId":"ace-q-0015"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"4df853b1bd2d2bcd19918dc63429095e49e83b12f4ff38d6a80436d138a81e11","itemId":"ace-q-0016"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"4f6f28936ae7c5b62c926eeaaa325a119bbe964656239afb4d14bdbb8ba536a4","itemId":"ace-q-0017"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"a18d8995ccf77ab781b9cb04d16444ea1f961fb8d335560f35e19d1761f9e51e","itemId":"ace-q-0018"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"396d9f873c4fdb2954397d52b317ab5a451c3fac0ab64eb1457b54fa87476f09","itemId":"ace-q-0019"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"851138206dc789f9c25572188218e26063778ac59d08cb0f49b9b456a43f1054","itemId":"ace-q-0020"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"e89de7a4d8e2ffd2111979d68add6211ab83af7f67a4293897f27b42bfa5bf73","itemId":"ace-q-0021"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"e9befa17947692d8daea5909ef71887a3a5f82be0735cd78b0e4551fbd8a4386","itemId":"ace-q-0022"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"16176ee24b24547a9028a165cb88134b4d667b6443af39310987c0c23c69d2d4","itemId":"ace-q-0023"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"4f224745cf6eba806b6d359d507c63b731c0b4782d5b14dd6587b3f7684f0416","itemId":"ace-q-0024"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"a569264caac6af92633e4bb5520d5ac2b8f05e6b7852d9fe1a957022bb8b8d97","itemId":"ace-q-0025"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"840df5e7b5ff8c0641f0a5aa0bf77d2f8da95ed30a6f509d67025b0cdb3e8581","itemId":"ace-q-0026"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"fb529c4a46bddd15626aaa189355dab730a17981769331697b65fcd187819c27","itemId":"ace-q-0027"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"30c54eab3ac8b86d602ea201693e7ccad8c7a3a7a39900886577b83a1754db74","itemId":"ace-q-0028"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"874617296524ad9fada54df142d0d0b0f13bebc920a7cfd77273634a393f9f88","itemId":"ace-q-0029"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"a26e744ae5047234ce22aa30aac3f609b1deb9b7c59eb87852634f582d5288b1","itemId":"ace-q-0030"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"6fd04d97da66c2210e838245bc466b72d0ca7f86ece5490101248055f5ceb2c5","itemId":"ace-q-0031"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"071c109f596710f21d6c1bdaa5c84048679a5749405cd1fa3449f01329d7b7d4","itemId":"ace-q-0032"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"465dd042416a2e41d010bf4a44a4bae4d31cc4ea14c8ebf2ccee5bac1f13c06b","itemId":"ace-q-0033"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"e19c52bacb8a7364db97edbdeb1095f515698905c80feeed0ab20009a1d39923","itemId":"ace-q-0034"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"c4a120248df7afee3f85f82a28db7850c1cc6677e3f895b2d9293ad21775e62a","itemId":"ace-q-0035"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"6eee6747bf295b22096c3769bc63fbe86ff364bd7bc18b6a91d33f8374d77255","itemId":"ace-q-0036"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"c9497da21839f039d67a187e93ae2d08d8ed14c2551cefd926e3c9072615e1b0","itemId":"ace-q-0037"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"265a8ff0505d05e9fc7a1273afd02d6929b3f85a5cfa28cf5bb42ebd0619b278","itemId":"ace-q-0038"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"a8207dd39891435f879895a857d0f32d4b167687c9be78905d8ffb7b515acf56","itemId":"ace-q-0039"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"73b2967f1ef417b1480aeb32e1914c69fa8bd8236936df774401d6318e24479f","itemId":"ace-q-0040"},{"approvalId":"approval:cloud-certification:gcp-ace-0007:technical:23432ff1bebb24b765568669abf2ba8ec73f952d5835fbfb09f0bc64ff2b8545","itemFingerprint":"73943c72912f53e4d3d59057bd86215de99a838a8be
